appVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rule:
    - host: cncamp.com
      http:
        paths:
        - path: "/order"
          pathType: Prefix
          backend:
            service:
              name: order-service
              port:
                number: 31054
     - host: cncamp.com
       http:
        paths:
        - path: "/shop"
          pathType: Prefix
          backend:
            service:
              name: shop-service
              port:
                number: 30657
      