apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: zuiweng518/gowebserver:v1.0


