apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLables:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.33
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 123456
        - name: MYSQL_USER
          value: go
        - name: MYSQL_PASSWORD
          value: 123456

