apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 1
  selector:
    matchLables:
      app: order
  templates:
    metadata:
      labels:
        app: order
    spec:
      container:
      - name: order
        image: zuiweng518/order:v1.0
