apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
      - name: shop
        image: zuiweng518/shop:v2.0
        volumeMounts:
        - name: shop-configmap
          mountPath: /conf
      volumes:
        - name: shop-configmap
          configMap:
            name: shop-configmap
